"""
VidyaSetu ERP — Complete Schema Migration
==========================================
Phase 1-11: All tables across all modules.
Run with: python -m alembic upgrade head
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = 'a001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── Core ─────────────────────────────────────────────────────
    op.create_table('roles',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('display_name', sa.String(200), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table('permissions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('module', sa.String(100), nullable=True),
        sa.Column('action', sa.String(100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table('users',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(100), nullable=False),
        sa.Column('email', sa.String(255), nullable=True),
        sa.Column('mobile', sa.String(15), nullable=True),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('hashed_password', sa.String(500), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('photo_path', sa.String(500), nullable=True),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.create_index('ix_users_username', 'users', ['username'])
    op.create_table('user_roles',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('role_id', sa.BigInteger(), sa.ForeignKey('roles.id'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('role_permissions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('role_id', sa.BigInteger(), sa.ForeignKey('roles.id'), nullable=False),
        sa.Column('permission_id', sa.BigInteger(), sa.ForeignKey('permissions.id'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('user_sessions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('token_hash', sa.String(500), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Settings ──────────────────────────────────────────────────
    op.create_table('system_settings',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('key', sa.String(200), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key'),
    )
    op.create_table('academic_years',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(20), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    # ── Students ─────────────────────────────────────────────────
    op.create_table('students',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('gr_number', sa.String(50), nullable=False),
        sa.Column('admission_number', sa.String(50), nullable=True),
        sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('full_name_marathi', sa.String(255), nullable=True),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('middle_name', sa.String(100), nullable=True),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('mother_name', sa.String(255), nullable=True),
        sa.Column('photo_path', sa.String(500), nullable=True),
        sa.Column('academic_year_id', sa.BigInteger(), sa.ForeignKey('academic_years.id'), nullable=True),
        sa.Column('standard', sa.String(10), nullable=False),
        sa.Column('division', sa.String(5), nullable=True),
        sa.Column('roll_number', sa.Integer(), nullable=True),
        sa.Column('dob', sa.Date(), nullable=True),
        sa.Column('gender', sa.String(10), nullable=True),
        sa.Column('blood_group', sa.String(5), nullable=True),
        sa.Column('nationality', sa.String(50), nullable=False, server_default='Indian'),
        sa.Column('religion', sa.String(50), nullable=True),
        sa.Column('caste', sa.String(100), nullable=True),
        sa.Column('category', sa.String(20), nullable=True),
        sa.Column('mother_tongue', sa.String(50), nullable=True),
        sa.Column('aadhaar_number', sa.String(12), nullable=True),
        sa.Column('father_name', sa.String(255), nullable=True),
        sa.Column('mother_name_full', sa.String(255), nullable=True),
        sa.Column('father_mobile', sa.String(15), nullable=True),
        sa.Column('mother_mobile', sa.String(15), nullable=True),
        sa.Column('guardian_name', sa.String(255), nullable=True),
        sa.Column('guardian_mobile', sa.String(15), nullable=True),
        sa.Column('mobile', sa.String(15), nullable=True),
        sa.Column('email', sa.String(255), nullable=True),
        sa.Column('address_line1', sa.String(500), nullable=True),
        sa.Column('village', sa.String(100), nullable=True),
        sa.Column('taluka', sa.String(100), nullable=True),
        sa.Column('district', sa.String(100), nullable=True),
        sa.Column('state', sa.String(100), nullable=False, server_default='Maharashtra'),
        sa.Column('pincode', sa.String(10), nullable=True),
        sa.Column('admission_date', sa.Date(), nullable=True),
        sa.Column('date_of_leaving', sa.Date(), nullable=True),
        sa.Column('tc_number', sa.String(50), nullable=True),
        sa.Column('tc_issued', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('student_id_saral', sa.String(50), nullable=True),
        sa.Column('pen_number', sa.String(20), nullable=True),
        sa.Column('apaar_id', sa.String(20), nullable=True),
        sa.Column('uses_transport', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('status', sa.String(20), nullable=False, server_default='active'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('gr_number'),
    )
    op.create_index('ix_students_gr_number', 'students', ['gr_number'])
    op.create_index('ix_students_standard', 'students', ['standard'])
    op.create_table('student_documents',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('document_type', sa.String(100), nullable=False),
        sa.Column('file_path', sa.String(500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Teachers ─────────────────────────────────────────────────
    op.create_table('teachers',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('employee_id', sa.String(50), nullable=False),
        sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('full_name_marathi', sa.String(255), nullable=True),
        sa.Column('photo_path', sa.String(500), nullable=True),
        sa.Column('dob', sa.Date(), nullable=True),
        sa.Column('gender', sa.String(10), nullable=True),
        sa.Column('mobile', sa.String(15), nullable=True),
        sa.Column('email', sa.String(255), nullable=True),
        sa.Column('designation', sa.String(100), nullable=True),
        sa.Column('subjects', sa.Text(), nullable=True),
        sa.Column('date_of_joining', sa.Date(), nullable=True),
        sa.Column('employee_type', sa.String(50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('employee_id'),
    )
    op.create_table('teacher_qualifications',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('teacher_id', sa.BigInteger(), sa.ForeignKey('teachers.id'), nullable=False),
        sa.Column('degree', sa.String(100), nullable=True),
        sa.Column('institution', sa.String(255), nullable=True),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('teacher_experience',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('teacher_id', sa.BigInteger(), sa.ForeignKey('teachers.id'), nullable=False),
        sa.Column('institution', sa.String(255), nullable=True),
        sa.Column('from_date', sa.Date(), nullable=True),
        sa.Column('to_date', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('teacher_leaves',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('teacher_id', sa.BigInteger(), sa.ForeignKey('teachers.id'), nullable=False),
        sa.Column('leave_type', sa.String(50), nullable=True),
        sa.Column('from_date', sa.Date(), nullable=True),
        sa.Column('to_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Finance ───────────────────────────────────────────────────
    op.create_table('fee_categories',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('name_marathi', sa.String(200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('fee_structures',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('standard', sa.String(10), nullable=False),
        sa.Column('fee_category_id', sa.BigInteger(), sa.ForeignKey('fee_categories.id'), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('student_fee_records',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('fee_category_id', sa.BigInteger(), sa.ForeignKey('fee_categories.id'), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('fee_payments',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('receipt_number', sa.String(50), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('payment_date', sa.Date(), nullable=False),
        sa.Column('payment_mode', sa.String(30), nullable=False, server_default='cash'),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('total_received', sa.Numeric(12, 2), nullable=False),
        sa.Column('fee_record_id', sa.BigInteger(), sa.ForeignKey('student_fee_records.id'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('receipt_number'),
    )
    op.create_table('fee_discounts',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('expenses',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('expense_date', sa.Date(), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Library ───────────────────────────────────────────────────
    op.create_table('lib_categories',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('name_marathi', sa.String(200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('lib_publishers',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(300), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('lib_authors',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(300), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('lib_books',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('accession_number', sa.String(50), nullable=False),
        sa.Column('title', sa.String(500), nullable=False),
        sa.Column('title_marathi', sa.String(500), nullable=True),
        sa.Column('isbn', sa.String(20), nullable=True),
        sa.Column('category_id', sa.BigInteger(), sa.ForeignKey('lib_categories.id'), nullable=True),
        sa.Column('publisher_id', sa.BigInteger(), sa.ForeignKey('lib_publishers.id'), nullable=True),
        sa.Column('total_copies', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('available_copies', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('accession_number'),
    )
    op.create_table('lib_members',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('member_type', sa.String(20), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=True),
        sa.Column('teacher_id', sa.BigInteger(), sa.ForeignKey('teachers.id'), nullable=True),
        sa.Column('member_number', sa.String(50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('member_number'),
    )
    op.create_table('lib_book_issues',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('book_id', sa.BigInteger(), sa.ForeignKey('lib_books.id'), nullable=False),
        sa.Column('member_id', sa.BigInteger(), sa.ForeignKey('lib_members.id'), nullable=False),
        sa.Column('issue_date', sa.Date(), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('return_date', sa.Date(), nullable=True),
        sa.Column('fine_amount', sa.Numeric(8, 2), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('lib_book_copies',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('book_id', sa.BigInteger(), sa.ForeignKey('lib_books.id'), nullable=False),
        sa.Column('copy_number', sa.String(50), nullable=True),
        sa.Column('condition', sa.String(20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Exams ────────────────────────────────────────────────────
    op.create_table('exam_types',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('name_marathi', sa.String(200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('exams',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(300), nullable=False),
        sa.Column('exam_type_id', sa.BigInteger(), sa.ForeignKey('exam_types.id'), nullable=True),
        sa.Column('academic_year_id', sa.BigInteger(), sa.ForeignKey('academic_years.id'), nullable=True),
        sa.Column('standard', sa.String(10), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('exam_subjects',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('exam_id', sa.BigInteger(), sa.ForeignKey('exams.id'), nullable=False),
        sa.Column('subject_name', sa.String(200), nullable=False),
        sa.Column('max_marks', sa.Numeric(6, 2), nullable=False),
        sa.Column('passing_marks', sa.Numeric(6, 2), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('student_marks',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('exam_subject_id', sa.BigInteger(), sa.ForeignKey('exam_subjects.id'), nullable=False),
        sa.Column('marks_obtained', sa.Numeric(6, 2), nullable=True),
        sa.Column('grade', sa.String(5), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('exam_results',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('exam_id', sa.BigInteger(), sa.ForeignKey('exams.id'), nullable=False),
        sa.Column('total_marks', sa.Numeric(8, 2), nullable=True),
        sa.Column('percentage', sa.Numeric(5, 2), nullable=True),
        sa.Column('grade', sa.String(5), nullable=True),
        sa.Column('result', sa.String(10), nullable=True),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Attendance ────────────────────────────────────────────────
    op.create_table('holidays',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('holiday_date', sa.Date(), nullable=False),
        sa.Column('holiday_type', sa.String(50), nullable=True),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('student_attendance',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('standard', sa.String(10), nullable=False),
        sa.Column('division', sa.String(5), nullable=True),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('period', sa.String(20), nullable=False, server_default='full_day'),
        sa.Column('status', sa.String(20), nullable=False, server_default='present'),
        sa.Column('marked_by', sa.BigInteger(), nullable=True),
        sa.Column('remarks', sa.String(300), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'date', 'period', name='uq_student_attendance'),
    )
    op.create_table('class_attendance_sessions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('standard', sa.String(10), nullable=False),
        sa.Column('division', sa.String(5), nullable=True),
        sa.Column('session_date', sa.Date(), nullable=False),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('is_marked', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('marked_by', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('teacher_attendance',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('teacher_id', sa.BigInteger(), sa.ForeignKey('teachers.id'), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='present'),
        sa.Column('check_in', sa.String(10), nullable=True),
        sa.Column('check_out', sa.String(10), nullable=True),
        sa.Column('remarks', sa.String(300), nullable=True),
        sa.Column('marked_by', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('teacher_id', 'date', name='uq_teacher_attendance'),
    )
    op.create_table('monthly_attendance_summary',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('student_id', sa.BigInteger(), sa.ForeignKey('students.id'), nullable=False),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('standard', sa.String(10), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('working_days', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('present_days', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('absent_days', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Timetable ────────────────────────────────────────────────
    op.create_table('timetable_periods',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('standard', sa.String(10), nullable=False),
        sa.Column('division', sa.String(5), nullable=True),
        sa.Column('day_of_week', sa.Integer(), nullable=False),
        sa.Column('period_number', sa.Integer(), nullable=False),
        sa.Column('subject', sa.String(200), nullable=True),
        sa.Column('teacher_id', sa.BigInteger(), sa.ForeignKey('teachers.id'), nullable=True),
        sa.Column('start_time', sa.String(10), nullable=True),
        sa.Column('end_time', sa.String(10), nullable=True),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Communication ────────────────────────────────────────────
    op.create_table('notices',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(500), nullable=False),
        sa.Column('title_marathi', sa.String(500), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('notice_type', sa.String(50), nullable=False, server_default='general'),
        sa.Column('target_audience', sa.String(100), nullable=False, server_default='all'),
        sa.Column('is_published', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('published_by', sa.BigInteger(), nullable=True),
        sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('sms_logs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('recipient_mobile', sa.String(15), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('message_templates',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('language', sa.String(10), nullable=False, server_default='english'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    # ── Office ────────────────────────────────────────────────────
    op.create_table('office_notices',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(500), nullable=False),
        sa.Column('title_marathi', sa.String(500), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('notice_type', sa.String(50), nullable=False, server_default='general'),
        sa.Column('is_published', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('published_by', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('visitors',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('visitor_name', sa.String(255), nullable=False),
        sa.Column('mobile', sa.String(15), nullable=True),
        sa.Column('purpose', sa.String(500), nullable=True),
        sa.Column('person_to_meet', sa.String(255), nullable=True),
        sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
        sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('complaints',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('complaint_number', sa.String(50), nullable=False),
        sa.Column('complainant_name', sa.String(255), nullable=True),
        sa.Column('subject', sa.String(500), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(30), nullable=False, server_default='open'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('complaint_number'),
    )
    op.create_table('admission_enquiries',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('enquiry_number', sa.String(50), nullable=False),
        sa.Column('enquiry_date', sa.Date(), nullable=False),
        sa.Column('student_name', sa.String(255), nullable=False),
        sa.Column('standard_applying_for', sa.String(10), nullable=False),
        sa.Column('status', sa.String(30), nullable=False, server_default='pending'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('enquiry_number'),
    )
    op.create_table('school_events',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(400), nullable=False),
        sa.Column('event_date', sa.Date(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('inward_register',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('inward_number', sa.String(50), nullable=False),
        sa.Column('received_date', sa.Date(), nullable=False),
        sa.Column('from_name', sa.String(300), nullable=True),
        sa.Column('subject', sa.String(500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('inward_number'),
    )

    # ── Inventory ─────────────────────────────────────────────────
    op.create_table('asset_categories',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('name_marathi', sa.String(200), nullable=True),
        sa.Column('parent_id', sa.BigInteger(), sa.ForeignKey('asset_categories.id'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('assets',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('asset_code', sa.String(50), nullable=False),
        sa.Column('name', sa.String(300), nullable=False),
        sa.Column('name_marathi', sa.String(300), nullable=True),
        sa.Column('category_id', sa.BigInteger(), sa.ForeignKey('asset_categories.id'), nullable=True),
        sa.Column('serial_number', sa.String(100), nullable=True),
        sa.Column('purchase_date', sa.Date(), nullable=True),
        sa.Column('purchase_price', sa.Numeric(14, 2), nullable=True),
        sa.Column('vendor', sa.String(300), nullable=True),
        sa.Column('warranty_expiry', sa.Date(), nullable=True),
        sa.Column('location', sa.String(200), nullable=True),
        sa.Column('condition', sa.String(20), nullable=False, server_default='good'),
        sa.Column('status', sa.String(20), nullable=False, server_default='active'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('asset_code'),
    )
    op.create_table('maintenance_records',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('asset_id', sa.BigInteger(), sa.ForeignKey('assets.id'), nullable=False),
        sa.Column('maintenance_date', sa.Date(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cost', sa.Numeric(12, 2), nullable=False, server_default='0'),
        sa.Column('vendor', sa.String(300), nullable=True),
        sa.Column('performed_by', sa.String(200), nullable=True),
        sa.Column('next_due_date', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('stock_items',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('item_code', sa.String(50), nullable=False),
        sa.Column('name', sa.String(300), nullable=False),
        sa.Column('name_marathi', sa.String(300), nullable=True),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('unit', sa.String(30), nullable=False, server_default='piece'),
        sa.Column('current_stock', sa.Numeric(12, 3), nullable=False, server_default='0'),
        sa.Column('minimum_stock', sa.Numeric(12, 3), nullable=False, server_default='0'),
        sa.Column('unit_cost', sa.Numeric(12, 2), nullable=True),
        sa.Column('location', sa.String(200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('item_code'),
    )
    op.create_table('stock_transactions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('stock_item_id', sa.BigInteger(), sa.ForeignKey('stock_items.id'), nullable=False),
        sa.Column('txn_type', sa.String(20), nullable=False),
        sa.Column('quantity', sa.Numeric(12, 3), nullable=False),
        sa.Column('balance_after', sa.Numeric(12, 3), nullable=False),
        sa.Column('reference', sa.String(200), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_by', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # ── Audit Log ────────────────────────────────────────────────
    op.create_table('audit_logs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('uuid', sa.String(36), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('user_name', sa.String(255), nullable=True),
        sa.Column('user_role', sa.String(100), nullable=True),
        sa.Column('action', sa.String(100), nullable=False),
        sa.Column('module', sa.String(100), nullable=False),
        sa.Column('entity_type', sa.String(100), nullable=True),
        sa.Column('entity_id', sa.String(100), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(50), nullable=True),
        sa.Column('device', sa.String(255), nullable=True),
        sa.Column('browser', sa.String(255), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uuid'),
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'])
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'])
    op.create_index('ix_audit_logs_module', 'audit_logs', ['module'])


def downgrade() -> None:
    # Drop in reverse dependency order
    op.drop_table('stock_transactions')
    op.drop_table('stock_items')
    op.drop_table('maintenance_records')
    op.drop_table('assets')
    op.drop_table('asset_categories')
    op.drop_table('inward_register')
    op.drop_table('school_events')
    op.drop_table('admission_enquiries')
    op.drop_table('complaints')
    op.drop_table('visitors')
    op.drop_table('office_notices')
    op.drop_table('message_templates')
    op.drop_table('sms_logs')
    op.drop_table('notices')
    op.drop_table('timetable_periods')
    op.drop_table('monthly_attendance_summary')
    op.drop_table('teacher_attendance')
    op.drop_table('class_attendance_sessions')
    op.drop_table('student_attendance')
    op.drop_table('holidays')
    op.drop_table('exam_results')
    op.drop_table('student_marks')
    op.drop_table('exam_subjects')
    op.drop_table('exams')
    op.drop_table('exam_types')
    op.drop_table('lib_book_issues')
    op.drop_table('lib_book_copies')
    op.drop_table('lib_members')
    op.drop_table('lib_books')
    op.drop_table('lib_authors')
    op.drop_table('lib_publishers')
    op.drop_table('lib_categories')
    op.drop_table('expenses')
    op.drop_table('fee_discounts')
    op.drop_table('fee_payments')
    op.drop_table('student_fee_records')
    op.drop_table('fee_structures')
    op.drop_table('fee_categories')
    op.drop_table('teacher_leaves')
    op.drop_table('teacher_experience')
    op.drop_table('teacher_qualifications')
    op.drop_table('teachers')
    op.drop_table('student_documents')
    op.drop_table('students')
    op.drop_table('academic_years')
    op.drop_table('system_settings')
    op.drop_table('user_sessions')
    op.drop_table('role_permissions')
    op.drop_table('user_roles')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('roles')
