"""
VidyaSetu ERP — Device Security Models
========================================
SQLAlchemy ORM models for:
  - UserDevice              : Registered trusted devices
  - LoginEvent              : Full login audit trail
  - LoginVerificationRequest: Pending new-device verifications
"""
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    BigInteger, Boolean, DateTime, Float, ForeignKey,
    Integer, String, Text
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import BaseModel, Base, utc_now


# ── Device Status Constants ───────────────────────────────────
class DeviceStatus:
    ACTIVE  = "ACTIVE"
    PENDING = "PENDING"
    REVOKED = "REVOKED"
    BLOCKED = "BLOCKED"


# ── Login Event Types ─────────────────────────────────────────
class LoginEventType:
    LOGIN_ATTEMPT                  = "LOGIN_ATTEMPT"
    LOGIN_SUCCESS                  = "LOGIN_SUCCESS"
    LOGIN_FAILED                   = "LOGIN_FAILED"
    NEW_DEVICE                     = "NEW_DEVICE"
    DEVICE_VERIFICATION_REQUESTED  = "DEVICE_VERIFICATION_REQUESTED"
    DEVICE_VERIFICATION_SUCCESS    = "DEVICE_VERIFICATION_SUCCESS"
    DEVICE_VERIFICATION_FAILED     = "DEVICE_VERIFICATION_FAILED"
    DEVICE_REVOKED                 = "DEVICE_REVOKED"
    PRIMARY_DEVICE_CHANGED         = "PRIMARY_DEVICE_CHANGED"
    LOGOUT                         = "LOGOUT"
    PASSWORD_CHANGED               = "PASSWORD_CHANGED"
    SUSPICIOUS_LOGIN               = "SUSPICIOUS_LOGIN"
    ACCOUNT_LOCKED                 = "ACCOUNT_LOCKED"
    DEVICE_REGISTERED              = "DEVICE_REGISTERED"
    # Temporary Device Login Events
    TEMPORARY_LOGIN_REQUESTED      = "TEMPORARY_LOGIN_REQUESTED"
    TEMPORARY_LOGIN_APPROVED       = "TEMPORARY_LOGIN_APPROVED"
    TEMPORARY_DEVICE_REGISTERED    = "TEMPORARY_DEVICE_REGISTERED"
    TEMPORARY_DEVICE_REVOKED       = "TEMPORARY_DEVICE_REVOKED"
    TEMPORARY_DEVICE_EXPIRED       = "TEMPORARY_DEVICE_EXPIRED"
    TEMPORARY_LOGIN_REJECTED       = "TEMPORARY_LOGIN_REJECTED"


# ── Verification Status ───────────────────────────────────────
class VerificationStatus:
    PENDING  = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    EXPIRED  = "EXPIRED"


# ═══════════════════════════════════════════════════════════════
# UserDevice
# ═══════════════════════════════════════════════════════════════

class UserDevice(BaseModel):
    """
    Registered device for a user.
    1 Primary + Maximum 2 Temporary devices per user.
    Exactly ONE primary per user (enforced in service and DB).
    
    Device identity is based on a cryptographically random installation ID
    generated by the client (browser or mobile app).
    We NEVER collect IMEI, MAC address, or other restricted hardware identifiers.
    """
    __tablename__ = "user_devices"

    # ── Ownership ─────────────────────────────────────────────
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True
    )

    # ── Device Identity ───────────────────────────────────────
    # High-entropy UUID generated on the client. Never a hardware identifier.
    device_installation_id: Mapped[str] = mapped_column(
        String(255), nullable=False, index=True
    )

    # ── Device Metadata ───────────────────────────────────────
    device_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)      # web | android | ios
    platform: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    manufacturer: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    model: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    os_version: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    app_version: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    browser_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    browser_version: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    user_agent: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    timezone: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    language: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)

    # ── Trust & Role State ─────────────────────────────────────
    is_primary: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_trusted: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_temporary: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    status: Mapped[str] = mapped_column(String(20), default=DeviceStatus.PENDING, nullable=False)
    revoke_reason: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # ── Timing & Expiration ───────────────────────────────────
    first_seen_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    last_seen_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    trusted_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    temporary_started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    temporary_expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Relationships ─────────────────────────────────────────
    user: Mapped["app.modules.auth.models.User"] = relationship(  # type: ignore[name-defined]
        "User", foreign_keys=[user_id], lazy="select"
    )
    login_events: Mapped[list["LoginEvent"]] = relationship(
        "LoginEvent", back_populates="device", lazy="select"
    )

    @property
    def display_name(self) -> str:
        """Human-readable device name for UI display."""
        if self.device_type == "web":
            parts = []
            if self.browser_name:
                parts.append(self.browser_name)
            if self.os_version:
                parts.append(self.os_version)
            return " on ".join(parts) if parts else "Web Browser"
        elif self.device_type in ("android", "ios"):
            parts = []
            if self.manufacturer:
                parts.append(self.manufacturer)
            if self.model:
                parts.append(self.model)
            return " ".join(parts) if parts else (self.device_type or "Mobile Device").title()
        return "Unknown Device"


# ═══════════════════════════════════════════════════════════════
# LoginEvent
# ═══════════════════════════════════════════════════════════════

class LoginEvent(BaseModel):
    """
    Immutable login audit event.
    Every significant security event is recorded here.
    Normal users cannot modify or delete these records.
    """
    __tablename__ = "login_events"

    # ── References ────────────────────────────────────────────
    user_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True, index=True
    )
    device_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("user_devices.id", ondelete="SET NULL"),
        nullable=True
    )
    # Groups all events belonging to one login attempt
    login_attempt_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)

    # ── Event Classification ──────────────────────────────────
    event_type: Mapped[str] = mapped_column(String(60), nullable=False, index=True)
    status: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)

    # ── Request Context ───────────────────────────────────────
    ip_address: Mapped[Optional[str]] = mapped_column(String(50), nullable=True, index=True)
    user_agent: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    device_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    platform: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    browser: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    os: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # ── Location (only when explicitly provided by client) ────
    approximate_location: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    latitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    longitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    location_accuracy: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # ── Event Metadata ────────────────────────────────────────
    login_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    verification_required: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    verification_method: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    risk_score: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    failure_reason: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # ── Relationships ─────────────────────────────────────────
    device: Mapped[Optional[UserDevice]] = relationship(
        "UserDevice", back_populates="login_events", lazy="select"
    )


# ═══════════════════════════════════════════════════════════════
# LoginVerificationRequest
# ═══════════════════════════════════════════════════════════════

class LoginVerificationRequest(Base):
    """
    Pending device verification.
    Created when a login is attempted from an unrecognized device.
    
    Security rules:
    - Token is single-use
    - Token expires after DEVICE_VERIFICATION_TOKEN_EXPIRE_MINUTES
    - Maximum 5 attempts before lockout
    - Token hash stored (never plaintext)
    """
    __tablename__ = "login_verification_requests"

    # UUID string PK — opaque, non-guessable
    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # ── References ────────────────────────────────────────────
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True
    )
    device_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("user_devices.id", ondelete="SET NULL"),
        nullable=True
    )
    login_attempt_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)

    # ── Verification Token (HASHED — never store plaintext) ───
    verification_token_hash: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # ── Status ────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default=VerificationStatus.PENDING
    )

    # ── Rate Limiting ─────────────────────────────────────────
    attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_attempts: Mapped[int] = mapped_column(Integer, default=5, nullable=False)

    # ── Timing ────────────────────────────────────────────────
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    verified_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    rejected_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Request Context ───────────────────────────────────────
    ip_address: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    user_agent: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ── Timestamps ────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utc_now, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utc_now, onupdate=utc_now, nullable=False
    )

    @property
    def is_expired(self) -> bool:
        return datetime.now(self.expires_at.tzinfo) > self.expires_at

    @property
    def is_exhausted(self) -> bool:
        return self.attempts >= self.max_attempts
